### ISSUE TITLE
Issues with `import_hgnc_dataset()`: HTTP error 404

### ISSUE THREAD

**Issue by nehawali21** [ramiromagno/hgnc#6]
Thank you so much for making such a handy package to extract the latest gene information from the HGNC! I'm a novice in R and data analysis, so this has been a wonderful way to get the newest details about genes that I'm evaluating in my data.

I didn't encounter issues when I last used this package a few months ago. However, I've run into some trouble this week despite not having edited the code.

When I try to run the following code to just initially load HGNC data: 
```
hgnc <- import_hgnc_dataset(latest_archive_url()) %>% 
  subset(status == "Approved") %>% 
  dplyr::select(c(symbol,
                  name,
                  locus_group,
                  locus_type,
                  ensembl_gene_id,
                  entrez_id))
```

I receive this error message:
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'subset': HTTP error 404.
```

To troubleshoot line by line, when I just run `import_hgnc_dataset(latest_archive_url())`, I receive the below error message, which suggested to me that perhaps the URL is an issue:
```
Error in open.connection(5L, "rb") : HTTP error 404.
```  

To test this, running `latest_archive_url()` yields the following without issues: 
```
[1] "https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/tsv/hgnc_complete_set.txt"
``` 
However, when I try to load this page into Chrome, I get an error that the URL was not found. 

Trying to manually recreate the URL in Chrome, I can only get as far as https://ftp.ebi.ac.uk/pub/databases/genenames/, as I don't see a sub-folder or file just called hgnc. 

The closest file path I can generate on my side is https://ftp.ebi.ac.uk/pub/databases/genenames/out_of_date_hgnc/tsv/hgnc_complete_set.txt. However, as the package should procure the latest HGNC gene names that are continually updated, I'm not sure if this would be the ideal file.

The code worked as of mid-August 2024, so perhaps `hgnc_complete_set.txt` was moved to the `out_of_date_hgnc` folder just afterwards which is why the URL changed and now the code doesn't work on my side. 

Does the URL in the package needs to be updated to this link, or to something else altogether? Or am I doing something wrong on my side? 

I'd be most grateful for your kind help with this! Thank you so much once again!

**Comment by ramiromagno** [comment]
hi @nehawali21:

Thanks for reporting this issue and taking the extra effort of looking into the root cause. Like you say, it could be that the URL changed. I will take a look.

**Comment by nehawali21** [comment]
Great, thank you so much for your prompt response! I've been looking at the HUGO site too (https://www.genenames.org/download/archive/) to see if there's a different link for the newest names. They list https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt as the current release file, but at least in my window this appears blank with just column names. 

I'm still a beginner with this all, so I'll leave this in the hands of a far more qualified person than me! Thank you so much again!

**Comment by ramiromagno** [comment]
It seems the new URL is: https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt. But the file seems to have only the header...

**Comment by ramiromagno** [comment]
Thanks, our messages just crossed :) Indeed, I already sent a message to the HGNC team about the empty file.

**Comment by ramiromagno** [comment]
They seem to be aware of the issue. Seemingly, by tomorrow it should be fixed.

**Comment by nehawali21** [comment]
Thank you so much again for kindly looking into this! Looks like the HGNC have indeed updated their initially empty file.


Just a quick follow up on this - I reloaded the `hgnc` package just now and still get an `Error in open.connection(3L, "rb") : HTTP error 404.` issue when I try to run my initial loading HGNC data code. Does the link used in the package need to be updated?

**Comment by ramiromagno** [comment]
hi @nehawali21:

Yes, indeed, the package needs to be updated. I will do it later today so by tomorrow you should be able to use the updated version.

**Comment by nehawali21** [comment]
Thank you so much! I haven't seen an updated package in RStudio so far; perhaps I'm looking in the wrong location?

**Comment by Charly776** [comment]
@nehawali21 

proabably you fixed it already, but for anyone else still having this issue: 

you can import the data set using this code:

import_hgnc_dataset(file="http://ftp.ebi.ac.uk/pub/databases/genenames/out_of_date_hgnc/tsv/hgnc_complete_set.txt")

**Comment by nehawali21** [comment]
Thanks for the tip! I haven't seen an updated package on my side, but I think this workaround would be great! I may switch the URL to "https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt" which is the current file site per the HGNC, but this is perhaps a good solution for the moment!

**Comment by nehawali21** [comment]
An update to this - the above workaround was working as of last month, but now when I run the below code I get the below error messages. The `.txt` link itself is valid as I can open it in Chrome. 

Are there any insights on how to resolve this?

Code: 
```
hgnc <- import_hgnc_dataset(file = "https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt")
```

Error messages:
```
Error in open.connection(5L, "rb") : cannot open the connection
In addition: Warning message:
Failed to open 'https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt': SSL certificate problem: self-signed certificate in certificate chain 
```

**Comment by ramiromagno** [comment]
hi @nehawali21 : 

could you please try with the latest dev version:

```R
pak::pak("ramiromagno/hgnc")
```

**Comment by nehawali21** [comment]
Thank you very much for your quick response. Even after installing the dev version I'm getting the same error messages.

**Comment by ramiromagno** [comment]
Strange... because on my end it seems to work.

Could you check hgnc package version?

``` r
library(hgnc)
hgnc <- import_hgnc_dataset(file = "https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt")
hgnc
#> # A tibble: 44,084 × 55
#>    hgnc_id    hgnc_id2 symbol    name     locus_group locus_type status location
#>    <chr>         <int> <chr>     <chr>    <chr>       <chr>      <chr>  <chr>   
#>  1 HGNC:5            5 A1BG      alpha-1… protein-co… gene with… Appro… 19q13.43
#>  2 HGNC:37133    37133 A1BG-AS1  A1BG an… non-coding… RNA, long… Appro… 19q13.43
#>  3 HGNC:24086    24086 A1CF      APOBEC1… protein-co… gene with… Appro… 10q11.23
#>  4 HGNC:7            7 A2M       alpha-2… protein-co… gene with… Appro… 12p13.31
#>  5 HGNC:27057    27057 A2M-AS1   A2M ant… non-coding… RNA, long… Appro… 12p13.31
#>  6 HGNC:23336    23336 A2ML1     alpha-2… protein-co… gene with… Appro… 12p13.31
#>  7 HGNC:41022    41022 A2ML1-AS1 A2ML1 a… non-coding… RNA, long… Appro… 12p13.31
#>  8 HGNC:41523    41523 A2ML1-AS2 A2ML1 a… non-coding… RNA, long… Appro… 12p13.31
#>  9 HGNC:8            8 A2MP1     alpha-2… pseudogene  pseudogene Appro… 12p13.31
#> 10 HGNC:30005    30005 A3GALT2   alpha 1… protein-co… gene with… Appro… 1p35.1  
#> # ℹ 44,074 more rows
#> # ℹ 47 more variables: location_sortable <chr>, alias_symbol <list>,
#> #   alias_name <list>, prev_symbol <list>, prev_name <list>, gene_group <list>,
#> #   gene_group_id <list>, date_approved_reserved <date>,
#> #   date_symbol_changed <date>, date_name_changed <date>, date_modified <date>,
#> #   entrez_id <int>, ensembl_gene_id <chr>, vega_id <chr>, ucsc_id <chr>,
#> #   ena <list>, refseq_accession <list>, ccds_id <list>, uniprot_ids <list>, …
```

``` r

sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.4.2 (2024-10-31)
#>  os       Arch Linux
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Europe/Lisbon
#>  date     2025-05-05
#>  pandoc   3.2 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/x86_64/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  bit           4.5.0.1 2024-12-03 [1] CRAN (R 4.4.2)
#>  bit64         4.5.2   2024-09-22 [1] CRAN (R 4.4.2)
#>  cachem        1.1.0   2024-05-16 [1] CRAN (R 4.4.0)
#>  cli           3.6.3   2024-06-21 [1] CRAN (R 4.4.2)
#>  crayon        1.5.2   2022-09-29 [1] CRAN (R 4.4.0)
#>  curl          6.2.1   2025-02-19 [1] CRAN (R 4.4.2)
#>  digest        0.6.35  2024-03-11 [1] CRAN (R 4.4.0)
#>  dplyr         1.1.4   2023-11-17 [1] CRAN (R 4.4.0)
#>  evaluate      0.24.0  2024-06-10 [1] CRAN (R 4.4.0)
#>  fansi         1.0.6   2023-12-08 [1] CRAN (R 4.4.0)
#>  fastmap       1.2.0   2024-05-15 [1] CRAN (R 4.4.0)
#>  fs            1.6.4   2024-04-25 [1] CRAN (R 4.4.0)
#>  generics      0.1.3   2022-07-05 [1] CRAN (R 4.4.0)
#>  glue          1.8.0   2024-09-30 [1] CRAN (R 4.4.2)
#>  hgnc        * 0.2.0   2025-05-05 [1] local
#>  hms           1.1.3   2023-03-21 [1] CRAN (R 4.4.0)
#>  htmltools     0.5.8.1 2024-04-04 [1] CRAN (R 4.4.0)
#>  knitr         1.46    2024-04-06 [1] CRAN (R 4.4.0)
#>  lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.4.0)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.4.0)
#>  memoise       2.0.1   2021-11-26 [1] CRAN (R 4.4.0)
#>  pillar        1.9.0   2023-03-22 [1] CRAN (R 4.4.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.4.0)
#>  purrr         1.0.4   2025-02-05 [1] CRAN (R 4.4.2)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.4.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.4.0)
#>  R.oo          1.26.0  2024-01-24 [1] CRAN (R 4.4.0)
#>  R.utils       2.12.3  2023-11-18 [1] CRAN (R 4.4.0)
#>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.4.0)
#>  readr         2.1.5   2024-01-10 [1] CRAN (R 4.4.0)
#>  reprex        2.1.0   2024-01-11 [1] CRAN (R 4.4.0)
#>  rlang         1.1.4   2024-06-04 [1] CRAN (R 4.4.2)
#>  rmarkdown     2.27    2024-05-17 [1] CRAN (R 4.4.0)
#>  rstudioapi    0.16.0  2024-03-24 [1] CRAN (R 4.4.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.4.0)
#>  stringi       1.8.4   2024-05-06 [1] CRAN (R 4.4.2)
#>  stringr       1.5.1   2023-11-14 [1] CRAN (R 4.4.2)
#>  styler        1.10.3  2024-04-07 [1] CRAN (R 4.4.0)
#>  tibble        3.2.1   2023-03-20 [1] CRAN (R 4.4.0)
#>  tidyselect    1.2.1   2024-03-11 [1] CRAN (R 4.4.0)
#>  tzdb          0.4.0   2023-05-12 [1] CRAN (R 4.4.0)
#>  utf8          1.2.4   2023-10-22 [1] CRAN (R 4.4.0)
#>  vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.4.0)
#>  vroom         1.6.5   2023-12-05 [1] CRAN (R 4.4.0)
#>  withr         3.0.2   2024-10-28 [1] CRAN (R 4.4.2)
#>  xfun          0.51    2025-02-19 [1] CRAN (R 4.4.2)
#>  yaml          2.3.8   2023-12-11 [1] CRAN (R 4.4.0)
#> 
#>  [1] /home/rmagno/R/x86_64-pc-linux-gnu-library/4.4
#>  [2] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

<sup>Created on 2025-05-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by nehawali21** [comment]
The hgnc package version I have is 0.1.5. I've pasted below the code and output if helpful.
```
> pak::pak("ramiromagno/hgnc")
! Using bundled GitHub PAT. Please add your own PAT using `gitcreds::gitcreds_set()`.
✔ Loading metadata database ... done                         
                                                                            
ℹ No downloads are needed
✔ 1 pkg + 43 deps: kept 44 [5.8s]

> library(hgnc)
> hgnc <- import_hgnc_dataset(file = "https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt")
Error in open.connection(3L, "rb") : cannot open the connection
In addition: Warning message:
Failed to open 'https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt': SSL certificate problem: self-signed certificate in certificate chain 
> sessioninfo::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.5.0 (2025-04-11)
 os       macOS Sequoia 15.4.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/New_York
 date     2025-05-05
 rstudio  2024.12.1+563 Kousa Dogwood (desktop)
 pandoc   NA
 quarto   1.5.57 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 bit           4.6.0   2025-03-06 [1] CRAN (R 4.5.0)
 bit64         4.6.0-1 2025-01-16 [1] CRAN (R 4.5.0)
 cachem        1.1.0   2024-05-16 [1] CRAN (R 4.5.0)
 callr         3.7.6   2024-03-25 [1] CRAN (R 4.5.0)
 cli           3.6.5   2025-04-23 [1] CRAN (R 4.5.0)
 crayon        1.5.3   2024-06-20 [1] CRAN (R 4.5.0)
 curl          6.2.2   2025-03-24 [1] CRAN (R 4.5.0)
 fastmap       1.2.0   2024-05-15 [1] CRAN (R 4.5.0)
 glue          1.8.0   2024-09-30 [1] CRAN (R 4.5.0)
 hgnc        * 0.1.5   2025-05-05 [1] Github (ramiromagno/hgnc@976120e)
 hms           1.1.3   2023-03-21 [1] CRAN (R 4.5.0)
 lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.5.0)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.5.0)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.5.0)
 pak           0.8.0.2 2025-04-08 [1] CRAN (R 4.5.0)
 pillar        1.10.2  2025-04-05 [1] CRAN (R 4.5.0)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.5.0)
 processx      3.8.6   2025-02-21 [1] CRAN (R 4.5.0)
 ps            1.9.1   2025-04-12 [1] CRAN (R 4.5.0)
 R6            2.6.1   2025-02-15 [1] CRAN (R 4.5.0)
 readr         2.1.5   2024-01-10 [1] CRAN (R 4.5.0)
 rlang         1.1.6   2025-04-11 [1] CRAN (R 4.5.0)
 rstudioapi    0.17.1  2024-10-22 [1] CRAN (R 4.5.0)
 sessioninfo   1.2.3   2025-02-05 [1] CRAN (R 4.5.0)
 tibble        3.2.1   2023-03-20 [1] CRAN (R 4.5.0)
 tidyselect    1.2.1   2024-03-11 [1] CRAN (R 4.5.0)
 tzdb          0.5.0   2025-03-15 [1] CRAN (R 4.5.0)
 vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.5.0)
 vroom         1.6.5   2023-12-05 [1] CRAN (R 4.5.0)

 [1] /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/library
 * ── Packages attached to the search path.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by ramiromagno** [comment]
what about this, does it work?

```R
curl::curl_download(
  url = "https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt",
  destfile = "hgnc.txt",
  handle = curl::new_handle(ssl_verifypeer = FALSE)
)
```

**Comment by nehawali21** [comment]
After the `curl` command and running 

```
library(hgnc) 
hgnc <- import_hgnc_dataset(file = "hgnc.txt")
``` 

I can now input the `hgnc` dataframe. However, I also get the below messages - will these cause issues with working with the `hgnc` dataframe?

```
Warning messages:                                                                                                
1: The following named parsers don't match the column names: rna_central_ids 
2: In func(file = file, ...) :
  Expected column(s) missing from HGNC dataset: rna_central_id
3: In func(file = file, ...) :
  Extra column(s) present in HGNC dataset: rna_central_ids
```

Additionally, are there plans to update the package in CRAN so that `import_hgnc_dataset()` can work as intended?

**Comment by ramiromagno** [comment]
Yes, I plan to update the package soon-ish... :) But it hasn't be easy to allocate the time.

Now, if the curl command worked, it means that there is something about the computer where you calling `import_hgnc_dataset()` that is not recognizing Google certificates... I can't really help more... With regards to the issue about `rna_central_ids` it should be fixed in the next update.

**Comment by nehawali21** [comment]
Thank you so much for kindly making the time to resolve this, I really appreciate it!

Hmm, looks like I need to investigate more then on my side regarding the Google certificates, particularly as the website itself can load in Chrome. Thank you again for your warm help on this!

**Comment by ramiromagno** [comment]
You're welcome! Let me know if you run into more problems.

**Comment by ramiromagno** [comment]
Development continues at https://github.com/patterninstitute/hgnc/.
